# Generated by Django 4.0 on 2021-12-13 22:35

import app.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=app.models.get_skills_default, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=app.models.get_skills_default, size=None)),
            ],
        ),
    ]
