# Generated by Django 4.0 on 2021-12-14 11:39

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=500),
        ),
    ]
