# Generated by Django 4.0 on 2021-12-14 12:06

import app.models
import django.contrib.postgres.fields
import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_candidate_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.citext.CICharField(max_length=200), default=app.models.get_skills_default, size=None),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.citext.CICharField(max_length=200), default=app.models.get_skills_default, size=None),
        ),
    ]
