# Generated by Django 4.0 on 2021-12-14 12:08

import app.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_candidate_skills_alter_job_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=app.models.get_skills_default, size=None),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=app.models.get_skills_default, size=None),
        ),
    ]
